export const tile = require("./assets/tile.png")

export const beef = require("./assets/beef.png")
export const cheese = require("./assets/cheese.png")
export const head = require("./assets/head.png")
export const onion = require("./assets/onion.png")
export const pickles = require("./assets/pickles.png")
export const salad = require("./assets/salad.png")
export const tail = require("./assets/tail.png")
export const tomato = require("./assets/tomato.png")
